service:
  port:
    http: 8025
    smtp: 1025
  nodePort:
    smtp: 1025

ingress:
  enabled: true
  spec:
    ingressClassName: traefik
  hosts:
    - host: mailhog.__IP__.nip.io
      paths: ["/"]
      port: 8025
