# values.yaml
rbac:
  enabled: true
service:
  externalIPs:
    - __IP__
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
ingressClass:
  enabled: true
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: true
ssl:
  enabled: true
  enforced: false
  defaultCert: __BASE64SSLCERT__
  defaultKey: __BASE64SSLPRIVATEKEY__
