# values.yaml
rbac:
  enabled: true
dashboard:
  enabled: true
  domain: traefik.__IP__.nip.io
  serviceType: NodePort
serviceType: NodePort
externalIP: __IP__
ssl:
  enabled: true
  enforced: false
  defaultCert: __BASE64SSLCERT__
  defaultKey: __BASE64SSLPRIVATEKEY__
