# values.yaml
rbac:
  enabled: true
service:
  externalIPs:
    - __IP__
ingressClass:
  enabled: true
  isDefaultClass: true
ssl:
  enabled: true
  enforced: false
  defaultCert: __BASE64SSLCERT__
  defaultKey: __BASE64SSLPRIVATEKEY__
