kind: Service
apiVersion: v1
metadata:
  name: gitlab-gitlab-shell-external
spec:
  selector:
    app: gitlab-shell
    release: gitlab
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 2222
  externalIPs:
    - __IP__
  type: NodePort
