apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitlab-shell
    chart: gitlab-shell-1.5.0
  name: gitlab-gitlab-shell-external
  selfLink: /api/v1/namespaces/default/services/gitlab-gitlab-shell
spec:
  externalIPs:
  - __IP__
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: gitlab-shell
    release: gitlab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
